### ISSUE TITLE
Reference to missing GrevmExecutorProvider

### ISSUE THREAD

**Issue by Chiplis** [Galxe/grevm#42]
The use-with-reth.md file mentions an implementation of the ParallelExecutorProvider trait with GrevmExecutorProvider, but the code itself is nowhere to be found.

**Comment by AshinGau** [comment]
Sorry for the link being invalid, it has been ready now: [Introduce Grevm to Reth](https://github.com/Galxe/grevm-reth/commit/9473670ab3c02e3699af1413f9c7bffc4bbbee45)

**Comment by Chiplis** [comment]
Thank you @AshinGau ! Was just about finished with my own reimplementation so it will be nice to see if they're similar :D

**Comment by Stumble** [comment]
Hey @Chiplis , thanks for checking out Grevm! We will release 2.0 algorithm very soon, hopefully would be much improved, espeacially for known limitations listed in our post. Stay tuned!
